export const IPC = {
  appVersion: 'app:version',
  projectRecent: 'project:recent',
  projectChooseLocation: 'project:choose-location',
  projectCreate: 'project:create',
  projectOpenDialog: 'project:open-dialog',
  projectOpenPath: 'project:open-path',
  projectInitial: 'project:initial',
  projectClose: 'project:close',
  projectTree: 'project:tree',
  projectGetState: 'project:get-state',
  projectSaveState: 'project:save-state',
  projectFilesChanged: 'project:files-changed',
  fileRead: 'file:read',
  fileSaveMarkdown: 'file:save-markdown',
  fileCreateMarkdown: 'file:create-markdown',
  fileCreateFolder: 'file:create-folder',
  fileRename: 'file:rename',
  fileMove: 'file:move',
  fileTrash: 'file:trash',
  fileImportFiles: 'file:import-files',
  fileReveal: 'file:reveal',
  fileUrl: 'file:url',
  fileApplyAiOperation: 'file:apply-ai-operation',
  sessionsList: 'sessions:list',
  sessionsSave: 'sessions:save',
  annotationsList: 'annotations:list',
  annotationsSave: 'annotations:save',
  searchQuery: 'search:query',
  searchCancel: 'search:cancel',
  searchProgress: 'search:progress',
  pdfPageText: 'pdf:page-text',
  pdfSearch: 'pdf:search',
  settingsGet: 'settings:get',
  settingsSave: 'settings:save',
  aiStart: 'ai:start',
  aiStop: 'ai:stop',
  aiStream: 'ai:stream'
} as const

export type IpcChannel = (typeof IPC)[keyof typeof IPC]
